version: '3'

services:
  spring-boot-backend:
    build: ./backend-java/spring-boot-app/
    ports:
      - "8080:8080"
  flask-backend:
    build: ./backend-python/flask-app/
    ports:
      - "5000:5000"
  react-frontend:
    build: ./frontend/react-gui/
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-backend
      - flask-backend